#! /usr/bin/env python
#-*-coding : utf-8 -*-
# px32-1
# PENDU

import os
import random


def get_mots():
	os.chdir('./wdir')
	flux = open('f_mots')
	mots = flux.read().split()
	flux.close()
	return mots

def parametrage(mots):
	mot = random.choice(mots).decode('utf-8')
	taille = len(mot)
	trou = '-'
	devine = trou * taille
	return mot, taille, trou, devine

def actualise(event) :
	global devine
	if P and trou in devine :
		if check_key(event) is 'ignore' : pass
		else:
			nouveau = valide(event.char.decode('utf-8').lower(), mot, devine)
			if devine != nouveau : devine = nouveau
			else : eval(P.pop(0))
			affiche()

def check_key(event):
	ignorelist = 'Shift_L Cancel BackSpace Tab Return Control_L Alt_L Pause Caps_Lock Escape Prior Next End Home Left Up Right Down Print Insert Delete F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 Num_Lock Scroll_Lock'.split()
	for i in ignorelist:
		if event.keysym==i : return 'ignore'
	return 'garde'

def valide(C, original, devine, R = '') :
	for x in range(taille) :
		if original [x] == C : R += original [x]
		else : R += devine [x]
	return R

def affiche() :
	L = len(P)
	LT.configure(text = devine)
	LP.configure(text = str(L))
	if not L : LM ['text'] = mot


mot, taille, trou, devine = parametrage(get_mots())

from Tkinter import *
top = Tk()
top.title("devine le mot")
top.bind("<Key>", actualise)

c = Canvas(top, bg='light grey', height=200, width=200)
c.pack(side = LEFT)

# la pendaison... une liste de dessins
P = [ 'c.create_line(40, 185, 140, 185, width=20, fill="maroon")',
	'c.create_line(70, 185, 70, 10, width=7, fill="maroon")',
	'c.create_line(66, 10, 129, 10, width=7, fill="maroon")',
	'c.create_line(127, 13, 127, 60, width=4, fill="yellow")',
	'c.create_oval(110, 30, 129, 49, width=1, fill="black")',
	'c.create_rectangle(116, 50, 136, 100, fill="black")',
	'c.create_line(120, 50, 100, 100, width=4, fill="black")',
	'c.create_line(136, 50, 146, 100, width=4, fill="black")',
	'c.create_line(120, 100, 120, 150, width=7, fill="black")',
	'c.create_line(133, 100, 133, 150, width=7, fill="black")' ]

Button(top, text='start', command=top.quit).pack(side=TOP)
Button(top, text='stop', command=top.quit).pack(side=TOP)

LT = Label(top, text=devine, fg='red') ; LT.pack()
LM = Label(top, text='', fg='red') ; LM.pack()
LP = Label(top, text=str(len(P)), fg='blue') ; LP.pack()

top.mainloop()
top.destroy()
